version: "3.8"

services:
  producer:
    build: ../../apps/event-driven-system/producer
    ports:
      - "5000:5000"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

  consumer:
    build: ../../apps/event-driven-system/consumer
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
